import React, { useState } from 'react';
import Button from 'react-bootstrap/Button';
import "../../../styles/TriviaSelectorStyle.css";

// Note: Code generated by AI
const TriviaSelector = ({ onSelect }) => {
    const [selectedMode, setSelectedMode] = useState('');

    const handleSelect = (mode) => {
        setSelectedMode(mode);
        if (onSelect) {
            onSelect(mode); // Notify parent component about the selection
        }
    };

    return (
        <div className={"main"}>
            <div className={"header"}>
                <p>OPTIONS</p>
            </div>
            <div className={"content"}>
                <div className={"option-container"}>
                    <div className={"option-label"}>
                        MODE
                    </div>
                    <div className={"option-selector"}>
                        <div className={"radio-container"}>
                            <div className="form-check">
                                <input className="form-check-input" type="radio" name="flexRadioDefault"
                                       id="flexRadioDefault1"/>
                                <label className="form-check-label" htmlFor="flexRadioDefault1">
                                    Single-Player
                                </label>
                            </div>
                            <div className="form-check">
                                <input className="form-check-input" type="radio" name="flexRadioDefault"
                                       id="flexRadioDefault2" checked/>
                                <label className="form-check-label" htmlFor="flexRadioDefault2">
                                    Multi-Player
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={"option-container"}>
                    <div className={"option-label"}>
                        NUMBER OF ROUNDS
                    </div>
                    <div className={"option-selector"}>
                        <input type="range" id="range" className="form-range" min="0" max="20"/>
                    </div>
                </div>
                <div className={"button-container"}>
                    <button type="button" id="start-button" className="btn btn-primary">START</button>
                </div>
            </div>


        </div>







        /*        <div className="d-flex justify-content-center gap-2">
                    <Button onClick={() => handleSelect('singlePlayer')} variant={selectedMode === 'singlePlayer'? 'primary' : 'outline-primary'}>
                        Single Player
                    </Button>
                    <Button onClick={() => handleSelect('multiplayer')} variant={selectedMode === 'multiplayer'? 'primary' : 'outline-primary'}>
                        Multiplayer
                    </Button>
                </div>*/
    );
};

export default TriviaSelector;